use_frameworks!

target 'SDWebImageLottiePlugin_Example' do
  platform :ios, '11.0'
  pod 'SDWebImageLottiePlugin', :path => '../'

  target 'SDWebImageLottiePlugin_Tests' do
    inherit! :search_paths
    pod 'SDWebImageLottiePlugin', :path => '../'
    
  end
end

target 'SDWebImageLottiePlugin_Example macOS' do
  platform :osx, '10.13'
  pod 'SDWebImageLottiePlugin', :path => '../'
end